/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class Infos extends javax.swing.JPanel {

    /**
     * Creates new form Infos
     */
    public Infos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLimgOuro = new javax.swing.JLabel();
        jLimgPrata = new javax.swing.JLabel();
        jLimgDourado = new javax.swing.JLabel();
        jLlblRecordes = new javax.swing.JLabel();
        jLlbOuro = new javax.swing.JLabel();
        jLlbPrata = new javax.swing.JLabel();
        jLlbBronze = new javax.swing.JLabel();
        jLblPontos = new javax.swing.JLabel();
        jLlbAtual = new javax.swing.JLabel();

        jLimgOuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/ouro.jpg"))); // NOI18N

        jLimgPrata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/prata.jpg"))); // NOI18N

        jLimgDourado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/bronze.jpg"))); // NOI18N

        jLlblRecordes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLlblRecordes.setText("Recordes");

        jLlbOuro.setText("0");

        jLlbPrata.setText("0");

        jLlbBronze.setText("0");

        jLblPontos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLblPontos.setText("Pontos da Partida");

        jLlbAtual.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLlblRecordes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblPontos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLimgDourado)
                                    .addComponent(jLimgPrata)
                                    .addComponent(jLimgOuro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLlbOuro)
                                    .addComponent(jLlbPrata)
                                    .addComponent(jLlbBronze)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLlbAtual)))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLlblRecordes)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLimgOuro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLlbOuro)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLimgPrata))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLlbPrata)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLimgDourado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLlbBronze)))
                .addGap(40, 40, 40)
                .addComponent(jLblPontos)
                .addGap(18, 18, 18)
                .addComponent(jLlbAtual)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblPontos;
    private javax.swing.JLabel jLimgDourado;
    private javax.swing.JLabel jLimgOuro;
    private javax.swing.JLabel jLimgPrata;
    private javax.swing.JLabel jLlbAtual;
    private javax.swing.JLabel jLlbBronze;
    private javax.swing.JLabel jLlbOuro;
    private javax.swing.JLabel jLlbPrata;
    private javax.swing.JLabel jLlblRecordes;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
