/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author CarlaRoberta
 */
public class Intermediario extends javax.swing.JFrame {

    /**
     * Creates new form Intermediario
     */
    public Intermediario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jq1 = new javax.swing.JLabel();
        jq2 = new javax.swing.JLabel();
        jq3 = new javax.swing.JLabel();
        jq4 = new javax.swing.JLabel();
        jq5 = new javax.swing.JLabel();
        jq6 = new javax.swing.JLabel();
        jq7 = new javax.swing.JLabel();
        jq8 = new javax.swing.JLabel();
        jq9 = new javax.swing.JLabel();
        jq10 = new javax.swing.JLabel();
        jq11 = new javax.swing.JLabel();
        jq12 = new javax.swing.JLabel();
        jq13 = new javax.swing.JLabel();
        jq14 = new javax.swing.JLabel();
        jq15 = new javax.swing.JLabel();
        jq16 = new javax.swing.JLabel();
        jq17 = new javax.swing.JLabel();
        jq18 = new javax.swing.JLabel();
        jq19 = new javax.swing.JLabel();
        jq20 = new javax.swing.JLabel();
        jq21 = new javax.swing.JLabel();
        jq22 = new javax.swing.JLabel();
        jq23 = new javax.swing.JLabel();
        jq24 = new javax.swing.JLabel();
        jq25 = new javax.swing.JLabel();
        jq26 = new javax.swing.JLabel();
        jq27 = new javax.swing.JLabel();
        jq28 = new javax.swing.JLabel();
        jq29 = new javax.swing.JLabel();
        jq30 = new javax.swing.JLabel();
        jq31 = new javax.swing.JLabel();
        jq32 = new javax.swing.JLabel();
        jq33 = new javax.swing.JLabel();
        jq34 = new javax.swing.JLabel();
        jq35 = new javax.swing.JLabel();
        jq36 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        jq18.setToolTipText("");

        jq19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        jq36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jq16)
                    .addComponent(jq11)
                    .addComponent(jq6)
                    .addComponent(jq1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq12)
                                .addGap(18, 18, 18)
                                .addComponent(jq13)
                                .addGap(18, 18, 18)
                                .addComponent(jq14)
                                .addGap(18, 18, 18)
                                .addComponent(jq15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq7)
                                .addGap(18, 18, 18)
                                .addComponent(jq8)
                                .addGap(18, 18, 18)
                                .addComponent(jq9)
                                .addGap(18, 18, 18)
                                .addComponent(jq10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq17)
                                .addGap(18, 18, 18)
                                .addComponent(jq18)
                                .addGap(18, 18, 18)
                                .addComponent(jq19)
                                .addGap(18, 18, 18)
                                .addComponent(jq20)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq29)
                                .addGap(18, 18, 18)
                                .addComponent(jq26)
                                .addGap(18, 18, 18)
                                .addComponent(jq31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jq35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq27)
                                .addGap(18, 18, 18)
                                .addComponent(jq22)
                                .addGap(18, 18, 18)
                                .addComponent(jq30)
                                .addGap(18, 18, 18)
                                .addComponent(jq34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq25)
                                .addGap(18, 18, 18)
                                .addComponent(jq24)
                                .addGap(18, 18, 18)
                                .addComponent(jq32)
                                .addGap(18, 18, 18)
                                .addComponent(jq36)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq2)
                        .addGap(18, 18, 18)
                        .addComponent(jq3)
                        .addGap(18, 18, 18)
                        .addComponent(jq4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jq5)
                        .addGap(18, 18, 18)
                        .addComponent(jq28)
                        .addGap(18, 18, 18)
                        .addComponent(jq21)
                        .addGap(18, 18, 18)
                        .addComponent(jq23)
                        .addGap(18, 18, 18)
                        .addComponent(jq33)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq5)
                            .addComponent(jq1)
                            .addComponent(jq2)
                            .addComponent(jq4)
                            .addComponent(jq3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jq6)
                            .addComponent(jq7)
                            .addComponent(jq8)
                            .addComponent(jq9)
                            .addComponent(jq10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq11)
                            .addComponent(jq12)
                            .addComponent(jq13)
                            .addComponent(jq14)
                            .addComponent(jq15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq16)
                            .addComponent(jq17)
                            .addComponent(jq18)
                            .addComponent(jq19)
                            .addComponent(jq20))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jq28)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jq21)
                                        .addComponent(jq23)
                                        .addComponent(jq33)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jq27)
                                    .addComponent(jq22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq30, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jq34))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq29)
                            .addComponent(jq26)
                            .addComponent(jq31)
                            .addComponent(jq35))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq25)
                            .addComponent(jq24)
                            .addComponent(jq32)
                            .addComponent(jq36))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intermediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intermediario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jq1;
    private javax.swing.JLabel jq10;
    private javax.swing.JLabel jq11;
    private javax.swing.JLabel jq12;
    private javax.swing.JLabel jq13;
    private javax.swing.JLabel jq14;
    private javax.swing.JLabel jq15;
    private javax.swing.JLabel jq16;
    private javax.swing.JLabel jq17;
    private javax.swing.JLabel jq18;
    private javax.swing.JLabel jq19;
    private javax.swing.JLabel jq2;
    private javax.swing.JLabel jq20;
    private javax.swing.JLabel jq21;
    private javax.swing.JLabel jq22;
    private javax.swing.JLabel jq23;
    private javax.swing.JLabel jq24;
    private javax.swing.JLabel jq25;
    private javax.swing.JLabel jq26;
    private javax.swing.JLabel jq27;
    private javax.swing.JLabel jq28;
    private javax.swing.JLabel jq29;
    private javax.swing.JLabel jq3;
    private javax.swing.JLabel jq30;
    private javax.swing.JLabel jq31;
    private javax.swing.JLabel jq32;
    private javax.swing.JLabel jq33;
    private javax.swing.JLabel jq34;
    private javax.swing.JLabel jq35;
    private javax.swing.JLabel jq36;
    private javax.swing.JLabel jq4;
    private javax.swing.JLabel jq5;
    private javax.swing.JLabel jq6;
    private javax.swing.JLabel jq7;
    private javax.swing.JLabel jq8;
    private javax.swing.JLabel jq9;
    // End of variables declaration//GEN-END:variables
}
