/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoria_Dificil extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoria_Dificil
     */
    public JogoMemoria_Dificil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_img1 = new javax.swing.JLabel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_img3 = new javax.swing.JLabel();
        lbl_img4 = new javax.swing.JLabel();
        lbl_img5 = new javax.swing.JLabel();
        lbl_img6 = new javax.swing.JLabel();
        lbl_img7 = new javax.swing.JLabel();
        lbl_img8 = new javax.swing.JLabel();
        lbl_img9 = new javax.swing.JLabel();
        lbl_img10 = new javax.swing.JLabel();
        lbl_img11 = new javax.swing.JLabel();
        lbl_img12 = new javax.swing.JLabel();
        lbl_img13 = new javax.swing.JLabel();
        lbl_img14 = new javax.swing.JLabel();
        lbl_img15 = new javax.swing.JLabel();
        lbl_img16 = new javax.swing.JLabel();
        lbl_img17 = new javax.swing.JLabel();
        lbl_img18 = new javax.swing.JLabel();
        lbl_img19 = new javax.swing.JLabel();
        lbl_img20 = new javax.swing.JLabel();
        lbl_img21 = new javax.swing.JLabel();
        lbl_img22 = new javax.swing.JLabel();
        lbl_img23 = new javax.swing.JLabel();
        lbl_img24 = new javax.swing.JLabel();
        lbl_img25 = new javax.swing.JLabel();
        lbl_img26 = new javax.swing.JLabel();
        lbl_img27 = new javax.swing.JLabel();
        lbl_img28 = new javax.swing.JLabel();
        lbl_img29 = new javax.swing.JLabel();
        lbl_img30 = new javax.swing.JLabel();
        lbl_img31 = new javax.swing.JLabel();
        lbl_img32 = new javax.swing.JLabel();
        lbl_img33 = new javax.swing.JLabel();
        lbl_img34 = new javax.swing.JLabel();
        lbl_img35 = new javax.swing.JLabel();
        lbl_img36 = new javax.swing.JLabel();
        lbl_img37 = new javax.swing.JLabel();
        lbl_img38 = new javax.swing.JLabel();
        lbl_img39 = new javax.swing.JLabel();
        lbl_img40 = new javax.swing.JLabel();
        lbl_img41 = new javax.swing.JLabel();
        lbl_img42 = new javax.swing.JLabel();
        lbl_img43 = new javax.swing.JLabel();
        lbl_img44 = new javax.swing.JLabel();
        lbl_img45 = new javax.swing.JLabel();
        lbl_img46 = new javax.swing.JLabel();
        lbl_img47 = new javax.swing.JLabel();
        lbl_img48 = new javax.swing.JLabel();
        lbl_img49 = new javax.swing.JLabel();
        lbl_img50 = new javax.swing.JLabel();
        lbl_img51 = new javax.swing.JLabel();
        lbl_img53 = new javax.swing.JLabel();
        lbl_img54 = new javax.swing.JLabel();
        lbl_img55 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(9, 6));

        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img1);

        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img2);

        lbl_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img3);

        lbl_img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img4);

        lbl_img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img5);

        lbl_img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img6);

        lbl_img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img7);

        lbl_img8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img8);

        lbl_img9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img9);

        lbl_img10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img10);

        lbl_img11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img11);

        lbl_img12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img12);

        lbl_img13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img13);

        lbl_img14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img14);

        lbl_img15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img15);

        lbl_img16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img16);

        lbl_img17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img17);

        lbl_img18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img18);

        lbl_img19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img19);

        lbl_img20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img20);

        lbl_img21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img21);

        lbl_img22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img22);

        lbl_img23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img23);

        lbl_img24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img24);

        lbl_img25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img25);

        lbl_img26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img26);

        lbl_img27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img27);

        lbl_img28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img28);

        lbl_img29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img29);

        lbl_img30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img30);

        lbl_img31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img31);

        lbl_img32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img32);

        lbl_img33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img33);

        lbl_img34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img34);

        lbl_img35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img35);

        lbl_img36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img36);

        lbl_img37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img37);

        lbl_img38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img38);

        lbl_img39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img39);

        lbl_img40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img40);

        lbl_img41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img41);

        lbl_img42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img42);

        lbl_img43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img43);

        lbl_img44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img44);

        lbl_img45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img45);

        lbl_img46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img46);

        lbl_img47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img47);

        lbl_img48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img48);

        lbl_img49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img49);

        lbl_img50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img50);

        lbl_img51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img51);

        lbl_img53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img53);

        lbl_img54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img54);

        lbl_img55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrogação.jpg"))); // NOI18N
        add(lbl_img55);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lbl_img10;
    private javax.swing.JLabel lbl_img11;
    private javax.swing.JLabel lbl_img12;
    private javax.swing.JLabel lbl_img13;
    private javax.swing.JLabel lbl_img14;
    private javax.swing.JLabel lbl_img15;
    private javax.swing.JLabel lbl_img16;
    private javax.swing.JLabel lbl_img17;
    private javax.swing.JLabel lbl_img18;
    private javax.swing.JLabel lbl_img19;
    private javax.swing.JLabel lbl_img2;
    private javax.swing.JLabel lbl_img20;
    private javax.swing.JLabel lbl_img21;
    private javax.swing.JLabel lbl_img22;
    private javax.swing.JLabel lbl_img23;
    private javax.swing.JLabel lbl_img24;
    private javax.swing.JLabel lbl_img25;
    private javax.swing.JLabel lbl_img26;
    private javax.swing.JLabel lbl_img27;
    private javax.swing.JLabel lbl_img28;
    private javax.swing.JLabel lbl_img29;
    private javax.swing.JLabel lbl_img3;
    private javax.swing.JLabel lbl_img30;
    private javax.swing.JLabel lbl_img31;
    private javax.swing.JLabel lbl_img32;
    private javax.swing.JLabel lbl_img33;
    private javax.swing.JLabel lbl_img34;
    private javax.swing.JLabel lbl_img35;
    private javax.swing.JLabel lbl_img36;
    private javax.swing.JLabel lbl_img37;
    private javax.swing.JLabel lbl_img38;
    private javax.swing.JLabel lbl_img39;
    private javax.swing.JLabel lbl_img4;
    private javax.swing.JLabel lbl_img40;
    private javax.swing.JLabel lbl_img41;
    private javax.swing.JLabel lbl_img42;
    private javax.swing.JLabel lbl_img43;
    private javax.swing.JLabel lbl_img44;
    private javax.swing.JLabel lbl_img45;
    private javax.swing.JLabel lbl_img46;
    private javax.swing.JLabel lbl_img47;
    private javax.swing.JLabel lbl_img48;
    private javax.swing.JLabel lbl_img49;
    private javax.swing.JLabel lbl_img5;
    private javax.swing.JLabel lbl_img50;
    private javax.swing.JLabel lbl_img51;
    private javax.swing.JLabel lbl_img53;
    private javax.swing.JLabel lbl_img54;
    private javax.swing.JLabel lbl_img55;
    private javax.swing.JLabel lbl_img6;
    private javax.swing.JLabel lbl_img7;
    private javax.swing.JLabel lbl_img8;
    private javax.swing.JLabel lbl_img9;
    // End of variables declaration//GEN-END:variables
}
