/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;
import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaForm extends javax.swing.JFrame {

    /**
     * Creates new form JogoMemoriaForm
     */
    public JogoMemoriaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jm1 = new javax.swing.JLabel();
        jm2 = new javax.swing.JLabel();
        jm3 = new javax.swing.JLabel();
        jm4 = new javax.swing.JLabel();
        jm5 = new javax.swing.JLabel();
        jm6 = new javax.swing.JLabel();
        jm7 = new javax.swing.JLabel();
        jm8 = new javax.swing.JLabel();
        jm9 = new javax.swing.JLabel();
        jm10 = new javax.swing.JLabel();
        jm11 = new javax.swing.JLabel();
        jm12 = new javax.swing.JLabel();
        jm13 = new javax.swing.JLabel();
        jm14 = new javax.swing.JLabel();
        jm15 = new javax.swing.JLabel();
        jm16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        jm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        jm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        jm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        jm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        jm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        jm7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        jm8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        jm9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        jm10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        jm11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        jm12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        jm13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        jm14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        jm15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        jm16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jm13)
                        .addGap(18, 18, 18)
                        .addComponent(jm14)
                        .addGap(18, 18, 18)
                        .addComponent(jm15)
                        .addGap(18, 18, 18)
                        .addComponent(jm16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jm9)
                        .addGap(18, 18, 18)
                        .addComponent(jm10)
                        .addGap(18, 18, 18)
                        .addComponent(jm11)
                        .addGap(18, 18, 18)
                        .addComponent(jm12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jm2)
                        .addGap(18, 18, 18)
                        .addComponent(jm6)
                        .addGap(18, 18, 18)
                        .addComponent(jm7)
                        .addGap(18, 18, 18)
                        .addComponent(jm8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jm1)
                        .addGap(18, 18, 18)
                        .addComponent(jm4)
                        .addGap(18, 18, 18)
                        .addComponent(jm5)
                        .addGap(18, 18, 18)
                        .addComponent(jm3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jm3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jm1)
                        .addComponent(jm4)
                        .addComponent(jm5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jm6)
                    .addComponent(jm2)
                    .addComponent(jm7)
                    .addComponent(jm8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jm10)
                    .addComponent(jm9)
                    .addComponent(jm11)
                    .addComponent(jm12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jm14)
                    .addComponent(jm13)
                    .addComponent(jm15)
                    .addComponent(jm16))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoMemoriaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jm1;
    private javax.swing.JLabel jm10;
    private javax.swing.JLabel jm11;
    private javax.swing.JLabel jm12;
    private javax.swing.JLabel jm13;
    private javax.swing.JLabel jm14;
    private javax.swing.JLabel jm15;
    private javax.swing.JLabel jm16;
    private javax.swing.JLabel jm2;
    private javax.swing.JLabel jm3;
    private javax.swing.JLabel jm4;
    private javax.swing.JLabel jm5;
    private javax.swing.JLabel jm6;
    private javax.swing.JLabel jm7;
    private javax.swing.JLabel jm8;
    private javax.swing.JLabel jm9;
    // End of variables declaration//GEN-END:variables
}
