/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoria_Intermediario extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoria_Intermediario
     */
    public JogoMemoria_Intermediario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl00 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl40 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl45 = new javax.swing.JLabel();
        lbl50 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridLayout(6, 6));

        lbl00.setBackground(new java.awt.Color(204, 204, 255));
        lbl00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl00);

        lbl01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl01);

        lbl02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl02);

        lbl03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl03);

        lbl04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl04);

        lbl05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl05);

        lbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl10);

        lbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl11);

        lbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl12);

        lbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl13);

        lbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl14);

        lbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl15);

        lbl20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl20);

        lbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl21);

        lbl22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl22);

        lbl23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl23);

        lbl24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl24);

        lbl25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl25);

        lbl30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl30);

        lbl31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl31);

        lbl32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl32);

        lbl33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl33);

        lbl34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl34);

        lbl35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl35);

        lbl40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl40);

        lbl41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl41);

        lbl42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl42);

        lbl43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl43);

        lbl44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl44);

        lbl45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl45);

        lbl50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl50);

        lbl51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl51);

        lbl52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl52);

        lbl53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl53);

        lbl54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl54);

        lbl55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/interrog.jpg"))); // NOI18N
        add(lbl55);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl55;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lbl00
     */
    public javax.swing.JLabel getLbl00() {
        return lbl00;
    }

    /**
     * @param lbl00 the lbl00 to set
     */
    public void setLbl00(javax.swing.JLabel lbl00) {
        this.lbl00 = lbl00;
    }

    /**
     * @return the lbl01
     */
    public javax.swing.JLabel getLbl01() {
        return lbl01;
    }

    /**
     * @param lbl01 the lbl01 to set
     */
    public void setLbl01(javax.swing.JLabel lbl01) {
        this.lbl01 = lbl01;
    }

    /**
     * @return the lbl02
     */
    public javax.swing.JLabel getLbl02() {
        return lbl02;
    }

    /**
     * @param lbl02 the lbl02 to set
     */
    public void setLbl02(javax.swing.JLabel lbl02) {
        this.lbl02 = lbl02;
    }

    /**
     * @return the lbl03
     */
    public javax.swing.JLabel getLbl03() {
        return lbl03;
    }

    /**
     * @param lbl03 the lbl03 to set
     */
    public void setLbl03(javax.swing.JLabel lbl03) {
        this.lbl03 = lbl03;
    }

    /**
     * @return the lbl04
     */
    public javax.swing.JLabel getLbl04() {
        return lbl04;
    }

    /**
     * @param lbl04 the lbl04 to set
     */
    public void setLbl04(javax.swing.JLabel lbl04) {
        this.lbl04 = lbl04;
    }

    /**
     * @return the lbl05
     */
    public javax.swing.JLabel getLbl05() {
        return lbl05;
    }

    /**
     * @param lbl05 the lbl05 to set
     */
    public void setLbl05(javax.swing.JLabel lbl05) {
        this.lbl05 = lbl05;
    }

    /**
     * @return the lbl10
     */
    public javax.swing.JLabel getLbl10() {
        return lbl10;
    }

    /**
     * @param lbl10 the lbl10 to set
     */
    public void setLbl10(javax.swing.JLabel lbl10) {
        this.lbl10 = lbl10;
    }

    /**
     * @return the lbl11
     */
    public javax.swing.JLabel getLbl11() {
        return lbl11;
    }

    /**
     * @param lbl11 the lbl11 to set
     */
    public void setLbl11(javax.swing.JLabel lbl11) {
        this.lbl11 = lbl11;
    }

    /**
     * @return the lbl12
     */
    public javax.swing.JLabel getLbl12() {
        return lbl12;
    }

    /**
     * @param lbl12 the lbl12 to set
     */
    public void setLbl12(javax.swing.JLabel lbl12) {
        this.lbl12 = lbl12;
    }

    /**
     * @return the lbl13
     */
    public javax.swing.JLabel getLbl13() {
        return lbl13;
    }

    /**
     * @param lbl13 the lbl13 to set
     */
    public void setLbl13(javax.swing.JLabel lbl13) {
        this.lbl13 = lbl13;
    }

    /**
     * @return the lbl14
     */
    public javax.swing.JLabel getLbl14() {
        return lbl14;
    }

    /**
     * @param lbl14 the lbl14 to set
     */
    public void setLbl14(javax.swing.JLabel lbl14) {
        this.lbl14 = lbl14;
    }

    /**
     * @return the lbl15
     */
    public javax.swing.JLabel getLbl15() {
        return lbl15;
    }

    /**
     * @param lbl15 the lbl15 to set
     */
    public void setLbl15(javax.swing.JLabel lbl15) {
        this.lbl15 = lbl15;
    }

    /**
     * @return the lbl20
     */
    public javax.swing.JLabel getLbl20() {
        return lbl20;
    }

    /**
     * @param lbl20 the lbl20 to set
     */
    public void setLbl20(javax.swing.JLabel lbl20) {
        this.lbl20 = lbl20;
    }

    /**
     * @return the lbl21
     */
    public javax.swing.JLabel getLbl21() {
        return lbl21;
    }

    /**
     * @param lbl21 the lbl21 to set
     */
    public void setLbl21(javax.swing.JLabel lbl21) {
        this.lbl21 = lbl21;
    }

    /**
     * @return the lbl22
     */
    public javax.swing.JLabel getLbl22() {
        return lbl22;
    }

    /**
     * @param lbl22 the lbl22 to set
     */
    public void setLbl22(javax.swing.JLabel lbl22) {
        this.lbl22 = lbl22;
    }

    /**
     * @return the lbl23
     */
    public javax.swing.JLabel getLbl23() {
        return lbl23;
    }

    /**
     * @param lbl23 the lbl23 to set
     */
    public void setLbl23(javax.swing.JLabel lbl23) {
        this.lbl23 = lbl23;
    }

    /**
     * @return the lbl24
     */
    public javax.swing.JLabel getLbl24() {
        return lbl24;
    }

    /**
     * @param lbl24 the lbl24 to set
     */
    public void setLbl24(javax.swing.JLabel lbl24) {
        this.lbl24 = lbl24;
    }

    /**
     * @return the lbl25
     */
    public javax.swing.JLabel getLbl25() {
        return lbl25;
    }

    /**
     * @param lbl25 the lbl25 to set
     */
    public void setLbl25(javax.swing.JLabel lbl25) {
        this.lbl25 = lbl25;
    }

    /**
     * @return the lbl30
     */
    public javax.swing.JLabel getLbl30() {
        return lbl30;
    }

    /**
     * @param lbl30 the lbl30 to set
     */
    public void setLbl30(javax.swing.JLabel lbl30) {
        this.lbl30 = lbl30;
    }

    /**
     * @return the lbl31
     */
    public javax.swing.JLabel getLbl31() {
        return lbl31;
    }

    /**
     * @param lbl31 the lbl31 to set
     */
    public void setLbl31(javax.swing.JLabel lbl31) {
        this.lbl31 = lbl31;
    }

    /**
     * @return the lbl32
     */
    public javax.swing.JLabel getLbl32() {
        return lbl32;
    }

    /**
     * @param lbl32 the lbl32 to set
     */
    public void setLbl32(javax.swing.JLabel lbl32) {
        this.lbl32 = lbl32;
    }

    /**
     * @return the lbl33
     */
    public javax.swing.JLabel getLbl33() {
        return lbl33;
    }

    /**
     * @param lbl33 the lbl33 to set
     */
    public void setLbl33(javax.swing.JLabel lbl33) {
        this.lbl33 = lbl33;
    }

    /**
     * @return the lbl34
     */
    public javax.swing.JLabel getLbl34() {
        return lbl34;
    }

    /**
     * @param lbl34 the lbl34 to set
     */
    public void setLbl34(javax.swing.JLabel lbl34) {
        this.lbl34 = lbl34;
    }

    /**
     * @return the lbl35
     */
    public javax.swing.JLabel getLbl35() {
        return lbl35;
    }

    /**
     * @param lbl35 the lbl35 to set
     */
    public void setLbl35(javax.swing.JLabel lbl35) {
        this.lbl35 = lbl35;
    }

    /**
     * @return the lbl40
     */
    public javax.swing.JLabel getLbl40() {
        return lbl40;
    }

    /**
     * @param lbl40 the lbl40 to set
     */
    public void setLbl40(javax.swing.JLabel lbl40) {
        this.lbl40 = lbl40;
    }

    /**
     * @return the lbl41
     */
    public javax.swing.JLabel getLbl41() {
        return lbl41;
    }

    /**
     * @param lbl41 the lbl41 to set
     */
    public void setLbl41(javax.swing.JLabel lbl41) {
        this.lbl41 = lbl41;
    }

    /**
     * @return the lbl42
     */
    public javax.swing.JLabel getLbl42() {
        return lbl42;
    }

    /**
     * @param lbl42 the lbl42 to set
     */
    public void setLbl42(javax.swing.JLabel lbl42) {
        this.lbl42 = lbl42;
    }

    /**
     * @return the lbl43
     */
    public javax.swing.JLabel getLbl43() {
        return lbl43;
    }

    /**
     * @param lbl43 the lbl43 to set
     */
    public void setLbl43(javax.swing.JLabel lbl43) {
        this.lbl43 = lbl43;
    }

    /**
     * @return the lbl44
     */
    public javax.swing.JLabel getLbl44() {
        return lbl44;
    }

    /**
     * @param lbl44 the lbl44 to set
     */
    public void setLbl44(javax.swing.JLabel lbl44) {
        this.lbl44 = lbl44;
    }

    /**
     * @return the lbl45
     */
    public javax.swing.JLabel getLbl45() {
        return lbl45;
    }

    /**
     * @param lbl45 the lbl45 to set
     */
    public void setLbl45(javax.swing.JLabel lbl45) {
        this.lbl45 = lbl45;
    }

    /**
     * @return the lbl50
     */
    public javax.swing.JLabel getLbl50() {
        return lbl50;
    }

    /**
     * @param lbl50 the lbl50 to set
     */
    public void setLbl50(javax.swing.JLabel lbl50) {
        this.lbl50 = lbl50;
    }

    /**
     * @return the lbl51
     */
    public javax.swing.JLabel getLbl51() {
        return lbl51;
    }

    /**
     * @param lbl51 the lbl51 to set
     */
    public void setLbl51(javax.swing.JLabel lbl51) {
        this.lbl51 = lbl51;
    }

    /**
     * @return the lbl52
     */
    public javax.swing.JLabel getLbl52() {
        return lbl52;
    }

    /**
     * @param lbl52 the lbl52 to set
     */
    public void setLbl52(javax.swing.JLabel lbl52) {
        this.lbl52 = lbl52;
    }

    /**
     * @return the lbl53
     */
    public javax.swing.JLabel getLbl53() {
        return lbl53;
    }

    /**
     * @param lbl53 the lbl53 to set
     */
    public void setLbl53(javax.swing.JLabel lbl53) {
        this.lbl53 = lbl53;
    }

    /**
     * @return the lbl54
     */
    public javax.swing.JLabel getLbl54() {
        return lbl54;
    }

    /**
     * @param lbl54 the lbl54 to set
     */
    public void setLbl54(javax.swing.JLabel lbl54) {
        this.lbl54 = lbl54;
    }

    /**
     * @return the lbl55
     */
    public javax.swing.JLabel getLbl55() {
        return lbl55;
    }

    /**
     * @param lbl55 the lbl55 to set
     */
    public void setLbl55(javax.swing.JLabel lbl55) {
        this.lbl55 = lbl55;
    }
}
