/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoria_Intermediario extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoria_Intermediario
     */
    public JogoMemoria_Intermediario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        img10 = new javax.swing.JLabel();
        img11 = new javax.swing.JLabel();
        img12 = new javax.swing.JLabel();
        img13 = new javax.swing.JLabel();
        img14 = new javax.swing.JLabel();
        img15 = new javax.swing.JLabel();
        img16 = new javax.swing.JLabel();
        img17 = new javax.swing.JLabel();
        img18 = new javax.swing.JLabel();
        img19 = new javax.swing.JLabel();
        img20 = new javax.swing.JLabel();
        img21 = new javax.swing.JLabel();
        img22 = new javax.swing.JLabel();
        img23 = new javax.swing.JLabel();
        img24 = new javax.swing.JLabel();
        img25 = new javax.swing.JLabel();
        img26 = new javax.swing.JLabel();
        img27 = new javax.swing.JLabel();
        img28 = new javax.swing.JLabel();
        img29 = new javax.swing.JLabel();
        img30 = new javax.swing.JLabel();
        img31 = new javax.swing.JLabel();
        img32 = new javax.swing.JLabel();
        img33 = new javax.swing.JLabel();
        img35 = new javax.swing.JLabel();
        img36 = new javax.swing.JLabel();
        img34 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm14.jpg"))); // NOI18N

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm15.jpg"))); // NOI18N

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm13.jpg"))); // NOI18N

        img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        img8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        img9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm12.jpeg"))); // NOI18N

        img10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm12.jpeg"))); // NOI18N

        img11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm14.jpg"))); // NOI18N

        img12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm13.jpg"))); // NOI18N

        img13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm10.jpg"))); // NOI18N

        img14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm15.jpg"))); // NOI18N

        img15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        img16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        img17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        img18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        img19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        img20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        img21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm9.jpg"))); // NOI18N

        img22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm9.jpg"))); // NOI18N

        img23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        img24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        img25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        img26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        img27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        img28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        img29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        img30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm18.jpg"))); // NOI18N

        img31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm18.jpg"))); // NOI18N

        img32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm17.jpg"))); // NOI18N

        img33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm16.jpg"))); // NOI18N

        img35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm17.jpg"))); // NOI18N

        img36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        img34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm16.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img31)
                        .addGap(18, 18, 18)
                        .addComponent(img32)
                        .addGap(18, 18, 18)
                        .addComponent(img33)
                        .addGap(18, 18, 18)
                        .addComponent(img34)
                        .addGap(18, 18, 18)
                        .addComponent(img35)
                        .addGap(18, 18, 18)
                        .addComponent(img36)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img1)
                                        .addGap(18, 18, 18)
                                        .addComponent(img2)
                                        .addGap(18, 18, 18)
                                        .addComponent(img3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(img7)
                                            .addComponent(img13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(img8)
                                                .addGap(18, 18, 18)
                                                .addComponent(img9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(img14)
                                                .addGap(18, 18, 18)
                                                .addComponent(img15)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(img5)
                                        .addGap(18, 18, 18)
                                        .addComponent(img6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img10)
                                        .addGap(18, 18, 18)
                                        .addComponent(img11)
                                        .addGap(18, 18, 18)
                                        .addComponent(img12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img16)
                                        .addGap(18, 18, 18)
                                        .addComponent(img17)
                                        .addGap(18, 18, 18)
                                        .addComponent(img18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(img19)
                                .addGap(18, 18, 18)
                                .addComponent(img20)
                                .addGap(18, 18, 18)
                                .addComponent(img21)
                                .addGap(18, 18, 18)
                                .addComponent(img22)
                                .addGap(18, 18, 18)
                                .addComponent(img23)
                                .addGap(18, 18, 18)
                                .addComponent(img24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(img25)
                                .addGap(18, 18, 18)
                                .addComponent(img26)
                                .addGap(18, 18, 18)
                                .addComponent(img27)
                                .addGap(18, 18, 18)
                                .addComponent(img28)
                                .addGap(18, 18, 18)
                                .addComponent(img29)
                                .addGap(18, 18, 18)
                                .addComponent(img30)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img4)
                    .addComponent(img5)
                    .addComponent(img6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(img1)
                        .addComponent(img2)
                        .addComponent(img3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img8)
                    .addComponent(img7)
                    .addComponent(img9)
                    .addComponent(img10)
                    .addComponent(img11)
                    .addComponent(img12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img13)
                    .addComponent(img14)
                    .addComponent(img15)
                    .addComponent(img16)
                    .addComponent(img17)
                    .addComponent(img18))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img19)
                    .addComponent(img20)
                    .addComponent(img21)
                    .addComponent(img22)
                    .addComponent(img23)
                    .addComponent(img24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img25)
                    .addComponent(img26)
                    .addComponent(img27)
                    .addComponent(img28)
                    .addComponent(img29)
                    .addComponent(img30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img32)
                    .addComponent(img31)
                    .addComponent(img33)
                    .addComponent(img34)
                    .addComponent(img35)
                    .addComponent(img36))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img10;
    private javax.swing.JLabel img11;
    private javax.swing.JLabel img12;
    private javax.swing.JLabel img13;
    private javax.swing.JLabel img14;
    private javax.swing.JLabel img15;
    private javax.swing.JLabel img16;
    private javax.swing.JLabel img17;
    private javax.swing.JLabel img18;
    private javax.swing.JLabel img19;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img20;
    private javax.swing.JLabel img21;
    private javax.swing.JLabel img22;
    private javax.swing.JLabel img23;
    private javax.swing.JLabel img24;
    private javax.swing.JLabel img25;
    private javax.swing.JLabel img26;
    private javax.swing.JLabel img27;
    private javax.swing.JLabel img28;
    private javax.swing.JLabel img29;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img30;
    private javax.swing.JLabel img31;
    private javax.swing.JLabel img32;
    private javax.swing.JLabel img33;
    private javax.swing.JLabel img34;
    private javax.swing.JLabel img35;
    private javax.swing.JLabel img36;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    // End of variables declaration//GEN-END:variables
}
