/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoria_Dificil extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoria_Dificil
     */
    public JogoMemoria_Dificil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_img1 = new javax.swing.JLabel();
        lbl_img2 = new javax.swing.JLabel();
        lbl_img3 = new javax.swing.JLabel();
        lbl_img4 = new javax.swing.JLabel();
        lbl_img5 = new javax.swing.JLabel();
        lbl_img6 = new javax.swing.JLabel();
        lbl_img7 = new javax.swing.JLabel();
        lbl_img8 = new javax.swing.JLabel();
        lbl_img9 = new javax.swing.JLabel();
        lbl_img10 = new javax.swing.JLabel();
        lbl_img11 = new javax.swing.JLabel();
        lbl_img12 = new javax.swing.JLabel();
        lbl_img13 = new javax.swing.JLabel();
        lbl_img14 = new javax.swing.JLabel();
        lbl_img15 = new javax.swing.JLabel();
        lbl_img16 = new javax.swing.JLabel();
        lbl_img17 = new javax.swing.JLabel();
        lbl_img18 = new javax.swing.JLabel();
        lbl_img19 = new javax.swing.JLabel();
        lbl_img20 = new javax.swing.JLabel();
        lbl_img21 = new javax.swing.JLabel();
        lbl_img22 = new javax.swing.JLabel();
        lbl_img23 = new javax.swing.JLabel();
        lbl_img24 = new javax.swing.JLabel();
        lbl_img25 = new javax.swing.JLabel();
        lbl_img26 = new javax.swing.JLabel();
        lbl_img27 = new javax.swing.JLabel();
        lbl_img28 = new javax.swing.JLabel();
        lbl_img29 = new javax.swing.JLabel();
        lbl_img30 = new javax.swing.JLabel();
        lbl_img31 = new javax.swing.JLabel();
        lbl_img32 = new javax.swing.JLabel();
        lbl_img33 = new javax.swing.JLabel();
        lbl_img34 = new javax.swing.JLabel();
        lbl_img35 = new javax.swing.JLabel();
        lbl_img36 = new javax.swing.JLabel();
        lbl_img37 = new javax.swing.JLabel();
        lbl_img38 = new javax.swing.JLabel();
        lbl_img39 = new javax.swing.JLabel();
        lbl_img40 = new javax.swing.JLabel();
        lbl_img41 = new javax.swing.JLabel();
        lbl_img42 = new javax.swing.JLabel();
        lbl_img43 = new javax.swing.JLabel();
        lbl_img44 = new javax.swing.JLabel();
        lbl_img45 = new javax.swing.JLabel();
        lbl_img46 = new javax.swing.JLabel();
        lbl_img47 = new javax.swing.JLabel();
        lbl_img48 = new javax.swing.JLabel();
        lbl_img49 = new javax.swing.JLabel();
        lbl_img50 = new javax.swing.JLabel();
        lbl_img51 = new javax.swing.JLabel();
        lbl_img53 = new javax.swing.JLabel();
        lbl_img54 = new javax.swing.JLabel();
        lbl_img55 = new javax.swing.JLabel();

        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        lbl_img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        lbl_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm1.png"))); // NOI18N

        lbl_img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        lbl_img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        lbl_img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm3.jpg"))); // NOI18N

        lbl_img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        lbl_img8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        lbl_img9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm2.jpg"))); // NOI18N

        lbl_img10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        lbl_img11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        lbl_img12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm4.jpg"))); // NOI18N

        lbl_img13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        lbl_img14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        lbl_img15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm5.jpg"))); // NOI18N

        lbl_img16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        lbl_img17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        lbl_img18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm6.jpg"))); // NOI18N

        lbl_img19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        lbl_img20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        lbl_img21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm7.png"))); // NOI18N

        lbl_img22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        lbl_img23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        lbl_img24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm8.jpg"))); // NOI18N

        lbl_img25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm9.jpg"))); // NOI18N

        lbl_img26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm9.jpg"))); // NOI18N

        lbl_img27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm9.jpg"))); // NOI18N

        lbl_img28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm10.jpg"))); // NOI18N

        lbl_img29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm10.jpg"))); // NOI18N

        lbl_img30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm10.jpg"))); // NOI18N

        lbl_img31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        lbl_img32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        lbl_img33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm11.jpg"))); // NOI18N

        lbl_img34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm12.jpeg"))); // NOI18N

        lbl_img35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm12.jpeg"))); // NOI18N

        lbl_img36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm12.jpeg"))); // NOI18N

        lbl_img37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm13.jpg"))); // NOI18N

        lbl_img38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm13.jpg"))); // NOI18N

        lbl_img39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm13.jpg"))); // NOI18N

        lbl_img40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm14.jpg"))); // NOI18N

        lbl_img41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm14.jpg"))); // NOI18N

        lbl_img42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm14.jpg"))); // NOI18N

        lbl_img43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm15.jpg"))); // NOI18N

        lbl_img44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm15.jpg"))); // NOI18N

        lbl_img45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm15.jpg"))); // NOI18N

        lbl_img46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm16.jpg"))); // NOI18N

        lbl_img47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm16.jpg"))); // NOI18N

        lbl_img48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm16.jpg"))); // NOI18N

        lbl_img49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm17.jpg"))); // NOI18N

        lbl_img50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm17.jpg"))); // NOI18N

        lbl_img51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm17.jpg"))); // NOI18N

        lbl_img53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm18.jpg"))); // NOI18N

        lbl_img54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm18.jpg"))); // NOI18N

        lbl_img55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/Jm18.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_img1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img11)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img10)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img4)
                                        .addGap(19, 19, 19)
                                        .addComponent(lbl_img6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img14)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img13))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_img37)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_img38))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbl_img25)
                                                .addComponent(lbl_img33))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_img31)
                                                .addComponent(lbl_img26)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_img44)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_img45))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbl_img51)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_img49)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_img21)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img19)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_img5)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img7)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img9)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_img15)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img16)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_img17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img32)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_img34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_img29)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_img24)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img23)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_img22)
                                    .addComponent(lbl_img30)
                                    .addComponent(lbl_img35)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img39)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img43)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img47)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_img41)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_img40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_img46)
                                            .addComponent(lbl_img54))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_img53)
                                            .addComponent(lbl_img48)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_img50)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_img55)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_img2)
                    .addComponent(lbl_img1)
                    .addComponent(lbl_img3)
                    .addComponent(lbl_img10)
                    .addComponent(lbl_img12)
                    .addComponent(lbl_img11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img6)
                    .addComponent(lbl_img4)
                    .addComponent(lbl_img5)
                    .addComponent(lbl_img7)
                    .addComponent(lbl_img9)
                    .addComponent(lbl_img8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img14)
                    .addComponent(lbl_img13)
                    .addComponent(lbl_img15)
                    .addComponent(lbl_img16)
                    .addComponent(lbl_img17)
                    .addComponent(lbl_img18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img19)
                    .addComponent(lbl_img20)
                    .addComponent(lbl_img21)
                    .addComponent(lbl_img22)
                    .addComponent(lbl_img23)
                    .addComponent(lbl_img24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img26)
                    .addComponent(lbl_img27)
                    .addComponent(lbl_img25)
                    .addComponent(lbl_img29)
                    .addComponent(lbl_img28)
                    .addComponent(lbl_img30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img33)
                    .addComponent(lbl_img31)
                    .addComponent(lbl_img32)
                    .addComponent(lbl_img34)
                    .addComponent(lbl_img35)
                    .addComponent(lbl_img36))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img38)
                    .addComponent(lbl_img37)
                    .addComponent(lbl_img39)
                    .addComponent(lbl_img40)
                    .addComponent(lbl_img41)
                    .addComponent(lbl_img42))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img45)
                    .addComponent(lbl_img43)
                    .addComponent(lbl_img44)
                    .addComponent(lbl_img46)
                    .addComponent(lbl_img47)
                    .addComponent(lbl_img48))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_img50)
                    .addComponent(lbl_img49)
                    .addComponent(lbl_img51)
                    .addComponent(lbl_img53)
                    .addComponent(lbl_img54)
                    .addComponent(lbl_img55))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lbl_img10;
    private javax.swing.JLabel lbl_img11;
    private javax.swing.JLabel lbl_img12;
    private javax.swing.JLabel lbl_img13;
    private javax.swing.JLabel lbl_img14;
    private javax.swing.JLabel lbl_img15;
    private javax.swing.JLabel lbl_img16;
    private javax.swing.JLabel lbl_img17;
    private javax.swing.JLabel lbl_img18;
    private javax.swing.JLabel lbl_img19;
    private javax.swing.JLabel lbl_img2;
    private javax.swing.JLabel lbl_img20;
    private javax.swing.JLabel lbl_img21;
    private javax.swing.JLabel lbl_img22;
    private javax.swing.JLabel lbl_img23;
    private javax.swing.JLabel lbl_img24;
    private javax.swing.JLabel lbl_img25;
    private javax.swing.JLabel lbl_img26;
    private javax.swing.JLabel lbl_img27;
    private javax.swing.JLabel lbl_img28;
    private javax.swing.JLabel lbl_img29;
    private javax.swing.JLabel lbl_img3;
    private javax.swing.JLabel lbl_img30;
    private javax.swing.JLabel lbl_img31;
    private javax.swing.JLabel lbl_img32;
    private javax.swing.JLabel lbl_img33;
    private javax.swing.JLabel lbl_img34;
    private javax.swing.JLabel lbl_img35;
    private javax.swing.JLabel lbl_img36;
    private javax.swing.JLabel lbl_img37;
    private javax.swing.JLabel lbl_img38;
    private javax.swing.JLabel lbl_img39;
    private javax.swing.JLabel lbl_img4;
    private javax.swing.JLabel lbl_img40;
    private javax.swing.JLabel lbl_img41;
    private javax.swing.JLabel lbl_img42;
    private javax.swing.JLabel lbl_img43;
    private javax.swing.JLabel lbl_img44;
    private javax.swing.JLabel lbl_img45;
    private javax.swing.JLabel lbl_img46;
    private javax.swing.JLabel lbl_img47;
    private javax.swing.JLabel lbl_img48;
    private javax.swing.JLabel lbl_img49;
    private javax.swing.JLabel lbl_img5;
    private javax.swing.JLabel lbl_img50;
    private javax.swing.JLabel lbl_img51;
    private javax.swing.JLabel lbl_img53;
    private javax.swing.JLabel lbl_img54;
    private javax.swing.JLabel lbl_img55;
    private javax.swing.JLabel lbl_img6;
    private javax.swing.JLabel lbl_img7;
    private javax.swing.JLabel lbl_img8;
    private javax.swing.JLabel lbl_img9;
    // End of variables declaration//GEN-END:variables
}
